### ISSUE TITLE
inigo-data.txt is not created anymore (Archlinux)

### ISSUE THREAD

**Issue by GeyerA** [evilbunny2008/weeWxWeatherApp#11]
Hi, I was using the Weewx and your extension for some months and since a few days, inigo-data.txt is not updated anymore. I re-installed Weewx from scratch adding your extension but is not created.
I am on 4.14.87-1-ARCH armv71 kernel 4.19.97-1-ARCH (PI4).

**Comment by evilbunny2008** [comment]
Have you checked /var/log/syslog for errors?

**Comment by GeyerA** [comment]
Actually no, since I was not able to find the log...let me try to google more to find the log locations...

**Comment by GeyerA** [comment]
Was not able to check the logs; however noticed that my TE923 stopped recording outside temperature and humidity. Since this is working again, the inigo-data is also again created. Seems depends on function of weather station....

**Comment by evilbunny2008** [comment]
Yes, without weeWX working, generating the Inigo report will also fail.

**Comment by GeyerA** [comment]
Hello,
I think your comment is wrong. weewx was working all the time. The data
from the weather station about humidity was just not coming in. All other
data was present. You should check the code that the file is still created
although some sensors might not send data as it happens when a battery gets
discharged...

**Comment by evilbunny2008** [comment]
The console on my weather station went wonky the other day during a lightning storm and lost track of the sensors and several templates stopped working until I reset the console and it found the sensors again.

I could add a lot of checks and it would create the data file, but the data would have null/None entries and no errors in the logs that are helpful in tracking down problems.

What OS are you using?
If it's debian based you can install "less" by going
`sudo apt-get install less`
then you can run
`less /var/log/syslog`
you can then skip to the end of the log and page up until you see errors.

**Comment by GeyerA** [comment]
Hi,
My point is that you will always run risk that one sensor is not returning
a value. I run a TFA which is pretty reliable but had to move all to get
the signals stable. Now, I have no clue why, lost that most stable signal
and just your extension stopped. Weewx statistics continued and I could see
that humidity was not there...
I am on Archlinux Pi4...

**Comment by GeyerA** [comment]
Hello,
btw, I have my weather station running data loaded into WU here is the 5
day forecast API do you think it is possible to add to your apk?
https://api.weather.com/v3/wx/forecast/daily/5day?geocode=49.894148,10.357377&format=json&units=m&language=en-UK&apiKey=c81e0532448d4e259e0532448dce25f6
Please do not post the API on Github...
Regards,
Andreas

**Comment by evilbunny2008** [comment]
> Hello, btw, I have my weather station running data loaded into WU here is the 5 day forecast API do you think it is possible to add to your apk? https://api.weather.com/v3/wx/forecast/daily/5day?geocode=XX.XXX,YY.YYY&format=json&units=m&language=en-UK&apiKey=XXXXXXX Please do not post the API on Github... Regards, Andreas

I haven't had a chance to do this yet but I just noticed you posted the API key to github when you replied to their emails.

**Comment by GeyerA** [comment]
Hello, I assumed so not how else would you be able to try. I would not
expect that a lot of people are following here. Anyhow, if you know that
you can not work on this just remove the comments with the API from the
thread on Git. Thanks!

**Comment by evilbunny2008** [comment]
I forgot I'd already written code for weather.com, use the following format:

fctype=weather.com
forecast=YY.YYY,XX.XXX

**Comment by GeyerA** [comment]
Hello,
thanks. I am however on Wunderground. Will this also work?

**Comment by evilbunny2008** [comment]
Didn't weather.com buy out wunderground and in turn IBM bought out weather.com?

**Comment by GeyerA** [comment]
Hello,
I have no clue actually...I can try whether it works...

**Comment by GeyerA** [comment]
Hi, I tried and got an java.ioFileNotFoundException
The string for 5day forecast (Wunderground) is like
https://api.weather.com/v3/wx/forecast/daily/5day?geocode=xx.xxxxxx,yy.yyyyyy7&format=json&units=m&language=en-US&apiKey=keyfromuser
The string in the error is having v2/turbo/v1dailyForecast ....

**Comment by evilbunny2008** [comment]
The app builds the url itself, you just need to supply the lat/lon

fctype=weather.com
forecast=YY.YYY,XX.XXX

**Comment by GeyerA** [comment]
I did

**Comment by evilbunny2008** [comment]
I upgraded the code to use the v3 api, I've uploaded a new version but it's not available yet on the play store. You can sideload a copy from the releases page if you wish.

**Comment by GeyerA** [comment]
Great, works.
Just thought about it, maybe good to update the README since WU works. Thanks again.
