### ISSUE TITLE
Radar URL not set or is still downloading

### ISSUE THREAD

**Issue by knight-of-ni** [evilbunny2008/weeWXWeatherApp#12]
I just installed v0.8.24 from the Google play store. I've read the installation instructions in the wiki, have configured `inigo-settings.txt`, and everything seems to work, except for the Radar map.

Following the [Radar URL instructions](https://github.com/evilbunny2008/weeWXWeatherApp/wiki/Radar-URLs) for WeatherUnderground, the radar and radtype lines are configured as follows:

```
radtype=image
radar=https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?num=6&type=N0R&mapx=400&mapy=240&brand=wui&delay=15&frame=0&scale=1&transx=0&transy=0&severe=0&smooth=0&centerx=400&centery=240&station=LSX&rainsnow=0&lightning=0&noclutter=0&showlabels=1&showstorms=0&rand=26366020
```

This url works as expected from a web browser. However, the app just returns `Radar URL is not set or is still downloading`.

As far as I can tell, my configuration is correct so I'm reaching out for help. Thanks!

**Comment by lizdodd** [comment]
On Mon, 17 Feb 2020 18:03:48 +0000 (UTC)
Andrew Bauer <notifications@github.com> wrote:

> I just installed v0.8.24 from the Google play store. I've read the
> installation instructions in the wiki, have configured
> `inigo-settings.txt`, and everything seems to work, except for the
> Radar map.
> 
> Following the [Radar URL
> instructions](https://github.com/evilbunny2008/weeWXWeatherApp/wiki/Radar-URLs)
> for WeatherUnderground, the radar and radtype lines are configured as
> follows:
> 
> ```
> radtype=image
> radar=https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?num=6&type=N0R&mapx=400&mapy=240&brand=wui&delay=15&frame=0&scale=1&transx=0&transy=0&severe=0&smooth=0&centerx=400&centery=240&station=LSX&rainsnow=0&lightning=0&noclutter=0&showlabels=1&showstorms=0&rand=26366020
> ```
> 
> This url works as expected from a web browser. However, the app just
> returns `Radar URL is not set or is still downloading`.
> 
> As far as I can tell, my configuration is correct so I'm reaching out
> for help. Thanks!
> 
> 
to help decide if it Weather Underground or another factor
would you try 

https://www.windy.com/38.636/-90.245?radar,38.548,-90.255,8,m:eJyadEK

Liz

**Comment by knight-of-ni** [comment]
Setting `radar=https://www.windy.com/38.636/-90.245?radar,38.548,-90.255,8,m:eJyadEK` produced the same message.  

I also tried weather.gov's radar and got the same result: `radar=https://radar.weather.gov/ridge/lite/N0R/LSX_loop.gif`

**Comment by evilbunny2008** [comment]
> Setting `radar=https://www.windy.com/38.636/-90.245?radar,38.548,-90.255,8,m:eJyadEK` produced the same message.
> 
> I also tried weather.gov's radar and got the same result: `radar=https://radar.weather.gov/ridge/lite/N0R/LSX_loop.gif`

Did you set radtype=webpage in your config for the windy url?

**Comment by knight-of-ni** [comment]
Yes, setting radtype to either `webpage` or `image` does not appear to make a difference:
```
radtype=webpage
radar=https://www.windy.com/38.636/-90.245?radar,38.548,-90.255,8,m:eJyadEK
```
I get the same result.

As a sidenote, I've got a webcam configured, and the webcam url works quite well.

Also note, since I am not using a custom url, I set the relevant line in inigo-settings.txt to `custom=`, with nothing after the equals.

**Comment by evilbunny2008** [comment]
> Yes, setting radtype to either `webpage` or `image` does not appear to make a difference:
> 
> ```
> radtype=webpage
> radar=https://www.windy.com/38.636/-90.245?radar,38.548,-90.255,8,m:eJyadEK
> ```
> 
> I get the same result.
> 
> As a sidenote, I've got a webcam configured, and the webcam url works quite well.
> 
> Also note, since I am not using a custom url, I set the relevant line in inigo-settings.txt to `custom=`, with nothing after the equals.

Did you reload settings in the app when you made changes?

The app only downloads and parses changes manually.

**Comment by evilbunny2008** [comment]
One other thing, I used the embedded URL in my config:

radtype=webpage
radar=https://embed.windy.com/embed2.html?lat=YY.YYY&lon=XX.XXX&zoom=9&level=surface&overlay=radar&menu=&message=true&marker=&calendar=&pressure=true&type=map&location=coordinates&detail=&detailLat=YY.YYY&detailLon=XX.XXX&metricWind=km%2Fh&metricTemp=%C2%B0C&radarRange=-1

**Comment by knight-of-ni** [comment]
Sorry for the delay. I was travelling all week for work.

I didn't realize the app cached the config, and needs to be reloaded after any change to inigo-settings. The wiki doesn't clearly sate this. It mentions refreshing by swiping down, which doesn't seem to be sufficient. Instead, after any change, one must hit the Save Settings button. I'm not criticizing. Instead, I'm making a case to get this added to the documentation.

Once I got past that, it was a matter of figuring out what radar looked best on my mobile device. 

Weatherunderground doesn't seem to load with `radtype=image`. It does load with `radtype=webpage` but then it doesn't scale to fit the screen.

Ultimately, I just went with your suggestion, which loads and scales to fit properly:

```
radtype=webpage
radar=https://embed.windy.com/embed2.html?lat=38.548&lon=-90.255&zoom=9&level=surface&overlay=radar&menu=&message=true&marker=&calendar=&pressure=true&type=map&location=coordinates&detail=&detailLat=38.548&detailLon=-90.255&metricWind=km%2Fh&metricTemp=%C2%B0C&radarRange=-1
```

Thanks for the help.

**Comment by evilbunny2008** [comment]
> I didn't realize the app cached the config, and needs to be reloaded after any change to inigo-settings. The wiki doesn't clearly sate this. It mentions refreshing by swiping down, which doesn't seem to be sufficient.

In you opinion, where or what should be added to the wiki to improve the documentation?

**Comment by knight-of-ni** [comment]
What I am suggesting is to add a note to the [InigoSettings.txt](https://github.com/evilbunny2008/weeWXWeatherApp/wiki/InigoSettings.txt) page, possibly at the end of the Overview section.

The note should alert the user that, after any change is made to the inigo-settings.txt file, the Save Settings button must be selected in the app, from the hidden menu on the left, to pick up the new changes.

**Comment by evilbunny2008** [comment]
I've updated the wiki page in the overview section to include a note in bold. I also added comment to the top of the example settings file.

**Comment by knight-of-ni** [comment]
Thanks!
