### ISSUE TITLE
Error in creation inigo-data.tmpl

### ISSUE THREAD

**Issue by CdfCastronno** [evilbunny2008/weeWxWeatherApp#14]
Hello, could you help me to analyze this error, i don't understand what i 'be wrong or forget
thanks
Gianni
May 30 23:50:27 raspberrypi weewx[575] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Inigo/inigo-data.txt.tmpl
May 30 23:50:27 raspberrypi weewx[575] ERROR weewx.cheetahgenerator: **** Reason: 'UnknownType' object is not subscriptable
May 30 23:50:27 raspberrypi weewx[575] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
May 30 23:50:27 raspberrypi weewx[575] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 322, in generate
May 30 23:50:27 raspberrypi weewx[575] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
May 30 23:50:27 raspberrypi weewx[575] ERROR weewx.cheetahgenerator: ****    File "_etc_weewx_skins_Inigo_inigo_data_txt_tmpl.py", line 791, in respond
May 30 23:50:27 raspberrypi weewx[575] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/units.py", line 1077, in raw
May 30 23:50:27 raspberrypi weewx[575] ERROR weewx.cheetahgenerator: ****      return self._raw_value_tuple[0]
May 30 23:50:27 raspberrypi weewx[575] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/units.py", line 1100, in _raw_value_tuple
May 30 23:50:27 raspberrypi weewx[575] ERROR weewx.cheetahgenerator: ****      vtx = self.converter.convert(self.value_t)
May 30 23:50:27 raspberrypi weewx[575] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/units.py", line 883, in convert
May 30 23:50:27 raspberrypi weewx[575] ERROR weewx.cheetahgenerator: ****      if val_t[1] is None and val_t[2] is None:
May 30 23:50:27 raspberrypi weewx[575] ERROR weewx.cheetahgenerator: ****  TypeError: 'UnknownType' object is not

**Comment by evilbunny2008** [comment]
Has this happened before or is this a new install? and is that the full error message? (the last line seems truncated)

**Comment by CdfCastronno** [comment]
Ciao, thank you for your fast reply.
after some hours i've understand my first error.
in weewx.conf the indigo entry was mixed (i don't know why, with other skins), is strange because 
it seems to me that the entry is automatically inserted after the installation, right?

is my first installation of Inigo

this is the current headache:
DEBUG weewx.manager: Daily summary version is 2.0
Jun  1 00:38:24 raspberrypi weewx[14288] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'TypeError'>'
Jun  1 00:38:24 raspberrypi weewx[14288] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Inigo/inigo-data.txt.tmpl
Jun  1 00:38:24 raspberrypi weewx[14288] ERROR weewx.cheetahgenerator: **** Reason: argument of type 'NoneType' is not iterable
Jun  1 00:38:24 raspberrypi weewx[14288] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Jun  1 00:38:24 raspberrypi weewx[14288] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 322, in generate
Jun  1 00:38:24 raspberrypi weewx[14288] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Jun  1 00:38:24 raspberrypi weewx[14288] ERROR weewx.cheetahgenerator: ****    File "_etc_weewx_skins_Inigo_inigo_data_txt_tmpl.py", line 233, in respond
Jun  1 00:38:24 raspberrypi weewx[14288] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/tags.py", line 457, in __getattr__
Jun  1 00:38:24 raspberrypi weewx[14288] ERROR weewx.cheetahgenerator: ****      vt = weewx.xtypes.get_scalar(obs_type, self.record, db_manager)
Jun  1 00:38:24 raspberrypi weewx[14288] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/xtypes.py", line 71, in get_scalar
Jun  1 00:38:24 raspberrypi weewx[14288] ERROR weewx.cheetahgenerator: ****      return xtype.get_scalar(obs_type, record, db_manager)
Jun  1 00:38:24 raspberrypi weewx[14288] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/wxservices.py", line 252, in get_scalar
Jun  1 00:38:24 raspberrypi weewx[14288] ERROR weewx.cheetahgenerator: ****      return getattr(self, method_name)(obs_type, record, db_manager)
Jun  1 00:38:24 raspberrypi weewx[14288] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/wxservices.py", line 274, in calc_cloudbase
Jun  1 00:38:24 raspberrypi weewx[14288] ERROR weewx.cheetahgenerator: ****      if 'outTemp' not in data or 'outHumidity' not in data:
Jun  1 00:38:24 raspberrypi weewx[14288] ERROR weewx.cheetahgenerator: ****  TypeError: argument of type 'NoneType' is not iterable
INFO weewx.cheetahgenerator: Generated 0 files for report Inigo in 0.39 seconds

i'm using SDR antenna witn WH1080

http://cdfcastronno.altervista.org/WEEWX/

Thanks for your attention
Gianni

**Comment by evilbunny2008** [comment]
It looks like outtemp or outhumidity isn't reporting in $current, I've added checks for this, let me know if this template works, if you are using a deb package, save it to /etc/weewx/skins/Inigo/inigo-data.txt.tmpl


[inigo-data.txt.tmpl.zip](https://github.com/evilbunny2008/weeWXWeatherApp/files/4710052/inigo-data.txt.tmpl.zip)

**Comment by CdfCastronno** [comment]
Ciao Evil,
with the new file all works, now i'm testing the different customization.
thanks a lot for you help!
Gianni
