### ISSUE TITLE
Self signed SSL certificate

### ISSUE THREAD

**Issue by castle1126** [evilbunny2008/weeWxWeatherApp#15]
Hi, I have a Weewx installation that is not publicly viewable, only viewable to systems on my LAN/Wifi at home.  I went through the setup of the app and get the following error:

javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found

I didn't have any plans for using a true SSL certificate via a vendor/etc.  Is there any way to make this work with your app?

Thanks!

**Comment by evilbunny2008** [comment]
Change the settings URL from https://.... to http://

**Comment by castle1126** [comment]
Thanks - I did that and clicked 'save', but continue to get the same error.

**Comment by evilbunny2008** [comment]
What about url's inside the settings file?

**Comment by castle1126** [comment]
Ah, overlooked that one.  Changed it there and all is well.  Thanks!!
