### ISSUE TITLE
Radar URL seems to not be working

### ISSUE THREAD

**Issue by castle1126** [evilbunny2008/weeWxWeatherApp#16]
In my inigo-settings.txt I have the following lines for the radar for my area:

radtype=image
radar=https://s.w-x.co/staticmaps/wu/wu/wxtype1200_cur/usbml/current.png

When I am in the WeeWx weather app on my Google Pixel 3XL the message "Radar URL not set or is still downloading.  You can go to settings to change."  This message always comes up - never showing me what the radar should be at that time.  I've restarted Apache as well as browsed to the settings file (browsing the file from a web browser shows the configuration lines are correct).

Is there something wrong with what I've attempted to do in the configuration?

**Comment by evilbunny2008** [comment]
The settings is cached, and you need to tell the app to redownload the settings. if you swipe from the left side of any screen the settings will open up.

**Comment by castle1126** [comment]
Ah thanks!  Yes it was cached, re-saved and works fine.  Thank you!!
