### ISSUE TITLE
Another working rainfall map

### ISSUE THREAD

**Issue by whiskerp** [evilbunny2008/weeWxWeatherApp#17]
This one is interactive - here is an example

radtype=webpage
radar=https://www.rainviewer.com/map.html?loc=51.0000,-0.5000,6&oFa=0&oC=1&oU=0&oCS=5&oF=0&oAP=0&rmt=1&c=0&o=80&lm=0&th=0&sm=1&sn=0

**Comment by evilbunny2008** [comment]
Thanks for the heads up :+1:, I added the URL and a screenshot to the wiki

https://github.com/evilbunny2008/weeWXWeatherApp/wiki/Radar-URLs#rainviewercom
