### ISSUE TITLE
Invalid URL / Android APP

### ISSUE THREAD

**Issue by BeNeDeLuX** [evilbunny2008/weeWxWeatherApp#2]
Hi,

i´ m unable to connect the Android APP with the needed Data.
The two files "settings.txt" and "data.txt" are without any problems accessible via the browser on the phone.
But the APP can´ connect to it.

Can i send you my URL via e-Mail that you can test it on your own? 
Don´t wont to make the URL that public.

Thanks!

// EDIT
Sent you an Mail with my URL.

**Comment by evilbunny2008** [comment]
I'm going to pushing out an update that ignores custom=https://example.com/mobile.html line
