### ISSUE TITLE
Icon pack present on device but not shown

### ISSUE THREAD

**Issue by JesterITA** [evilbunny2008/weeWxWeatherApp#20]
Hi all! 
I have a problem with the app that's not showing the forecast icons even if the folder "icons" is present on the device.
I'm using yahoo service.
Here's a couple of images to clarify.
Any suggestions?
![files](https://user-images.githubusercontent.com/8188627/115018175-d7b37c00-9eb7-11eb-951d-bf9ab858018c.jpg)
![app](https://user-images.githubusercontent.com/8188627/115018177-d84c1280-9eb7-11eb-81fe-75a86901f974.jpg)

**Comment by evilbunny2008** [comment]
Due to google locking android down I was forced to relocate the icons. Have you tried opening the settings panel (swipe from the left side of the screen) and hit save settings.

**Comment by JesterITA** [comment]
Yep, i tried that but nothing shown up.
I also tried to check/uncheck the "Use icons" and finally deleted and reinstalled the app. 
Nothing worked.

**Comment by evilbunny2008** [comment]
What phone/OS/etc ?

**Comment by JesterITA** [comment]
Yes, right, i forgot.
Redmi Note 7 with Android 10

**Comment by evilbunny2008** [comment]
Looks like yahoo updated their icons, I'm looking for replacements...

**Comment by evilbunny2008** [comment]
Turned out was a bug I introduced when changing the paths for the icons for yahoo, pushed out a new version but it's pending a review, or grab it from the release section:

https://github.com/evilbunny2008/weeWXWeatherApp/releases/tag/0.9.5

**Comment by JesterITA** [comment]
Great! Now it's working!
Thanks for the immediate response!
