### ISSUE TITLE
weeWXWeatherApp Fails to connect or download

### ISSUE THREAD

**Issue by GeorgeJetson99** [evilbunny2008/weeWxWeatherApp#22]
weeWXWeatherApp Fails to connect or download the settings from yo......

I am running the Weewx server on my local network.  Not accessible from WWW.  It is able to see the WWW for updates etc.  Weewx works and updates fine.

On my phone I can access the inigo-settings.txt file via the browser but not when I am using the weeWXWeatherApp.  It just fails to connect.

I get the feeling that I am missing something, but I don't know what. 

Can you assist?

**Comment by evilbunny2008** [comment]
If you don't mind, please email me the settings url to weather@odiousapps.com

**Comment by GeorgeJetson99** [comment]
After some advice from evilbunny2008 I reinstalled everything and it is now working.  I assume that I missed something during the first install.
