### ISSUE TITLE
YR integration to change format

### ISSUE THREAD

**Issue by GeorgeJetson99** [evilbunny2008/weeWxWeatherApp#23]
I wanted to use the YR forecast, but they have updated their website and there is no link to the "Free Data" and XML.  I found a link to the OLD webpages and there they have information about the changes. https://retro.yr.no/place/Australia/Victoria/Benalla/data.html
They are suggesting a Java script and that XML will be discontinued.

**Comment by evilbunny2008** [comment]
Judging by this:

https://developer.yr.no/doc/GettingStarted/

Everything is moving to https://api.met.no and is going from xml to json, json is nicer to work with I'll try and get an update out soon

I'm guessing but I bet they get their forecasts from BoM.gov.au

**Comment by evilbunny2008** [comment]
I just uploaded a new build v0.9.11 to the google play store and it supports met.no forecasts, I've left code for yr.no forecasts in, but it'll stop working February 2022.
