### ISSUE TITLE
Openweathermap api link is wrong

### ISSUE THREAD

**Issue by Volgi84** [evilbunny2008/weeWxWeatherApp#24]
First I wanted to say thanks for the app. It is really nice to be able to access your own weather data!
The url to the openweathermap seems to be wrong in the documentation. It states 
_forecast=https://api.openweathermap.org/data/2.5/forecast/daily?lat=-33.87&lon=151.21&appid=<api key>_
for the url but on the openweathermap site it states
https://api.openweathermap.org/data/2.5/forecast?lat=-33.87&lon=151.21&appid=<api key>  so "/daily" is not included. 
At least that is the case for the free plan.  
When I enter the url in the web browser, I see the JSON object. However, in the app I see only the spinning update indicator without actually updating the forecast.

**Comment by evilbunny2008** [comment]
Looking at their pricing page: https://openweathermap.org/full-price#current 7 day forecast/daily is included.

**Comment by Volgi84** [comment]
Ok, I see. I was looking at a different pricing page.
