### ISSUE TITLE
weewx widget not auto-updating

### ISSUE THREAD

**Issue by spacelama** [evilbunny2008/weeWxWeatherApp#27]
I have just done a migration of my weewx server, and also updated my phone at very similar time.  Alas, one of those has caused my weewx widget on my pixel 7 phone with Android 14, to stop polling for data every 5 minutes.   When I first click on the widget, the app attempts to open then crashes straight away (or at least it did until this morning, when I ensured my app was up-to-date as well, and I haven't seen a crash since, but I've seen the lack of updating).  I then click on the widget again, and it opens and updates some time later (sometimes an explicit refresh pull down is needed).

My weewx/inigo-settings.txt is still valid (unchanged from the old server), and my webserver is sending correct looking ETAG and Last-Modified headers.  I see in the help that I should go into settings to get it to repoll for that file if it's changed (it hasn't), and I can't seem to *find* any settings (and I don't want to clear-data just yet)!  There is no long-press on the widget to get into settings, and starting the app starts the app, complete without settings hamburger, tab or menu.

The only difference I can think of in the data being sent out was that inigo-data.txt file was without the ephem data for a day, but after fixing that, the problem hasn't come good.  I have ensured that battery optimisation is turned off on weewx weather app (battery optimisation was "normal" previously when it was working but thought I better ensure it was on "unoptimised" just to make sure).

Data and settings are here:
https://rather.puzzling.org/weewx/inigo-data.txt 
https://rather.puzzling.org/weewx/inigo-settings.txt

**Comment by evilbunny2008** [comment]
Android 14 has restrictions on apps waking up to save battery and it's becoming increasingly so, I've tried to fix this in app v1.0.16, please check that's the version you are running.

**Comment by spacelama** [comment]
Yeah I've been on 1.0.16 for 12 hours or so.  Android is turning to rubbish.  Similar requirements to tasker, so I was hoping those guidelines would be sufficient.  Odd that it didn't manifest until the hour I cutover to my new server.

**Comment by evilbunny2008** [comment]
What happens if you side load it from github, ie no play store making changes to the manifest?

https://github.com/evilbunny2008/weeWXWeatherApp/releases/download/1.0.16/app-release.apk

Unfortunately my phone only has Android 13
