### ISSUE TITLE
Support basic auth protected weewx

### ISSUE THREAD

**Issue by leaberry** [evilbunny2008/weeWxWeatherApp#3]
I run most of my stuff behind nginx with basic auth. It would be nice if this app supported basic auth with a checkbox (Use Basic Auth) and a username/password field.

I'm a Python guy, did Java a while ago, but I did some research and It looks like this would override every `url` connection.  

```
Authenticator.setDefault (new Authenticator() {
    protected PasswordAuthentication getPasswordAuthentication() {
        return new PasswordAuthentication ("username", "password".toCharArray());
    }
});
```

**Comment by evilbunny2008** [comment]
I'm not 100% sure how to do it yet, I'm hoping adding it to the url might work.

**Comment by evilbunny2008** [comment]
Thanks for the code pointer, I applied the changes to the code that downloads settings.txt and data.txt. As for custom page, sending it a URL with a username and password embedded seems to work, so I didn't need to change that.

Once v0.3.0 become live in the play store you'll be able to do https://username:password@example.com/weewx/settings.txt and the same schema can be used for data.txt.

**Comment by leaberry** [comment]
Just updated and it works great! Thanks for adding that.
