### ISSUE TITLE
[feature request] transparent background for widget ?

### ISSUE THREAD

**Issue by bonjour81** [evilbunny2008/weeWxWeatherApp#4]
Hi there!
I discover your great app ! 
I'm not sure if it's the right way (let me know if not), but I would like to share a suggestion for a feature.

Would it be possible to add a few options for the widget, like transparent background, and maybe some tuning for colors? 
I use a dark background, then, transparent widget would need a white font.

Previously, I used this widget: https://play.google.com/store/apps/details?id=ales.veluscek.weatherstation&hl=fr
It used to work fine with weewx if you provide a suitable cumulus format txt file.

**Comment by evilbunny2008** [comment]
I started out using a transparent background but I couldn't read the text as well, my background is in one of the screen shots. I can certainly add options to the app, I'll try to get something working today.

**Comment by evilbunny2008** [comment]
I just uploaded code to do colour picking for both the background and text colour from the settings page. The top slider is for alpha, which sets how opaque or transparent the background/foreground are.

**Comment by bonjour81** [comment]
Works great!
