### ISSUE TITLE
Request for alternative forecast source

### ISSUE THREAD

**Issue by AussieCodeKing71** [evilbunny2008/weeWxWeatherApp#6]
Love the app - thanks for the great work.
Like a number of weewx users I utilize the forecast plugin to generate my own forecast data and pages on my full site. It can generate mobile friendly forecast pages. I'm currently using the custom part of the app to view my own mobile forecast page. 
Do you think it would be possible to provide an option to utilise our own pre-generated pages in place of the current app generated one? 
Another option could be to write a new report in weewx to feed our existing forecast data to the app to allow the app to generate the existing view.

**Comment by evilbunny2008** [comment]
> Like a number of weewx users I utilize the forecast plugin to generate my own forecast data and pages on my full site. It can generate mobile friendly forecast pages. I'm currently using the custom part of the app to view my own mobile forecast page.

Is this the plugin?
https://github.com/weewx/weewx/wiki/forecasting

If so where are you sourcing the data from?

Are you aware there is now 17 forecast options in the app?

> Another option could be to write a new report in weewx to feed our existing forecast data to the app to allow the app to generate the existing view.

I'd be in favour of this rather than trying to load a web page as this would then be able to display on both weather tab and forecast/radar tab. Preferably in JSON format as it requires the least processing.

**Comment by AussieCodeKing71** [comment]
> Is this the plugin?
> https://github.com/weewx/weewx/wiki/forecasting

Yes this is the plugin

> If so where are you sourcing the data from?

Currently using WU using my specific GPS coords, but due to impending closure of their API I am investigating using alternative sources. Unfortunately at the moment some of the sources in your app are not available through the weewx plugin (eg weatherzone, Aus BOM, darksky, etc).

> Are you aware there is now 17 forecast options in the app?

Yes I was aware of the large number of options in the app, but forecasts are typically 2 degrees C lower in winter and up to 4 degrees C lower in the summer than what ends up being the maximum at my location. Accordingly on my weewx install I correct the provided forecast data to account for this bias. I did this after some work monitoring my outdoor readings and finding they are accurate within 1 degree C of nearly all PWS stations nearby.

> I'd be in favour of this rather than trying to load a web page as this would then be able to display on both weather tab and forecast/radar tab. Preferably in JSON format as it requires the least processing.

This doesn't surprise me as the more I thought about this suggestion the more I thought this might be the way it ends up going.

**Comment by evilbunny2008** [comment]
> Currently using WU using my specific GPS coords, but due to impending closure of their API I am investigating using alternative sources. Unfortunately at the moment some of the sources in your app are not available through the weewx plugin (eg weatherzone, Aus BOM, darksky, etc).

Last I heard WU API was closing on the 31st and you had to pay to use weather.com instead.

> Yes I was aware of the large number of options in the app, but forecasts are typically 2 degrees C lower in winter and up to 4 degrees C lower in the summer than what ends up being the maximum at my location. Accordingly on my weewx install I correct the provided forecast data to account for this bias. I did this after some work monitoring my outdoor readings and finding they are accurate within 1 degree C of nearly all PWS stations nearby.

There is a BoM forecast plugin for weeWX (Ausearch extension), although I can't seem to find a link to it at the moment, but this page references it:

https://github.com/dcapslock/weewx-responsive-skin/wiki/BOM-Lookup-Helper-Spreadsheet

There is also a darksky option if using the belchertownweather skin
