### ISSUE TITLE
SSL error: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by gldickens3** [evilbunny2008/weeWxWeatherApp#9]
I have comodo SSL certificates on my servers which have been working flawlessly for years but everytime I try to connect to initally download the inigo-settings.txt file I get the following error message:

javax.net.ssl.SSLHandshakeException:java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

Please advise what I should do.

Thanks,

Gordon

**Comment by evilbunny2008** [comment]
The SSL handling is dealt with by the OS, and without knowing the site I can't test, you can email me at weather@odiousapps.com
